# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# The default config of moveit does not take into account the jerk limits, the RuckigTrajectorySmoothing adapter must be
# added to the planning pipeline to support jerk limits

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 17.929068
    has_jerk: true
    max_jerk: 3757.777778
  joint_a2:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 1.324527
    has_jerk: true
    max_jerk: 3391.182265
  joint_a3:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 1.931703
    has_jerk: true
    max_jerk: 1362.865183
  joint_a4:
    has_velocity_limits: true
    max_velocity: 4.014255
    has_acceleration_limits: true
    max_acceleration: 20.760275
    has_jerk: true
    max_jerk: 606.319878
  joint_a5:
    has_velocity_limits: true
    max_velocity: 4.537856
    has_acceleration_limits: true
    max_acceleration: 17.729259
    has_jerk: true
    max_jerk: 598.681915
  joint_a6:
    has_velocity_limits: true
    max_velocity: 7.504909
    has_acceleration_limits: true
    max_acceleration: 98.845225
    has_jerk: true
    max_jerk: 145.557710
