controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

#    forward_command_controller:
#      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

    command_interfaces:
      - position

    state_interfaces:
      - position



# forward_command_controller:
#  ros__parameters:
#    joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6
#    interface_name: position

